services:
  - type: web
    name: llts-app
    env: python
    buildCommand: "cd .. && pip install -r LLTS/requirements.txt"
    startCommand: "gunicorn backend.app:app"
    envVars:
      - key: FLASK_ENV
        value: production
